language: python

python: 
  - "3.5"

env:
  global:
    - LIBRAW_GIT="git://github.com/LibRaw/LibRaw.git"
    - LIBRAW_CMAKE_GIT="git://github.com/LibRaw/LibRaw-cmake.git"
  matrix:
    - USE_LATEST_LIBRAW=true
    - USE_LATEST_LIBRAW=false
    
git:
  submodules: false

before_install:
  - travis_retry sudo apt-get update

install:
  - if [ $USE_LATEST_LIBRAW == true ]; then
      cd .. ;
      git clone $LIBRAW_GIT ;
      git clone $LIBRAW_CMAKE_GIT ;
      cp -R LibRaw-cmake/* LibRaw ;
      cd LibRaw ;
      git checkout `git describe --abbrev=0 --tags` ;
      cmake . -DENABLE_EXAMPLES=OFF -DENABLE_RAWSPEED=OFF ;
      make ;
      sudo make install ;
      echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/99local.conf ;
      sudo ldconfig ;
      cd ../rawpy ;
    else
      travis_retry sudo apt-get install libraw-dev ;
    fi
  - travis_retry sudo apt-get install libfreeimage-dev
  # scikit-image requires scipy
  - pip install scipy opencv-python
  - pip install -r dev-requirements.txt
  # output what's installed
  - pip freeze
  - python setup.py sdist
  - pip install dist/*.tar.gz

script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../test
  - cd ..

after_success:
  - if [ $USE_LATEST_LIBRAW == true ]; then
      pip install travispy ;
      travis_retry python -c "import os; from travispy import TravisPy; t = TravisPy.github_auth(os.environ['GITHUB_TOKEN']); t.build(t.branch('mac-wheels', 'letmaik/rawpy').id).restart()" ;
    fi

before_deploy:
  # otherwise sphinx would fail
  - python setup.py build_ext --inplace
  - pip install sphinx

deploy:
  provider: pypi
  user: letmaik
  password:
    secure: "Gi+qCKpRNFjlvpOxBXjSNAq4yDhlSXfUUl9RZaOSdER+YURbc9/AMlfUuyOvpi09tAgwGnn9Hn3z7NqqjNV9auTcD30viMnevNbiyJaE2O/bw75FU9HqFmTM/OR7UVJp4sNtxtXy1Zp5CxmMnzRCjV3stQ9iaG9aJOV3sbUzDTQ="
  on:
    tags: true
    condition: $USE_LATEST_LIBRAW = false
